### PR TITLE
minor edits chapter 10

### PR DESCRIPTION
**Pull request by hollykennedy**
grammar and typos

### CODE REVIEW

**Comment by AndrewRathbun** [comment]
@bgrundy feel free to take a look!

**Comment by bgrundy** [comment]
Thanks.  I could use a review like that on the LinuxLEO guide!  It all looks fine to me.  Much appreciated.

**Comment by AndrewRathbun** [comment]
> Thanks. I could use a review like that on the LinuxLEO guide! It all looks fine to me. Much appreciated.

If you got that on GitHub, we could probably make it happen!

**Comment by bgrundy** [comment]
It's on Github, not a public project though.  And it's currently written in Latex.  I'm probably going to switch it to asciidoc at some point though.

**Comment by hollykennedy** [comment]
I’d be happy to help! I’m in LE, too. Just holler :)

**Pull request merged**
